# Generated by Django 2.1.7 on 2019-03-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gradeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_id', models.CharField(max_length=30, verbose_name='课程号')),
                ('subject', models.CharField(max_length=30, verbose_name='课程名称')),
                ('property', models.CharField(max_length=30, verbose_name='课程性质')),
                ('grade', models.CharField(max_length=30, verbose_name='分数')),
            ],
        ),
        migrations.CreateModel(
            name='student_Id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xuehao', models.CharField(max_length=30, verbose_name='学号')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
