# Generated by Django 2.2 on 2019-10-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kcmc', models.CharField(max_length=50, verbose_name='课程名称')),
                ('ls', models.CharField(max_length=50, verbose_name='老师')),
                ('kcdd', models.CharField(max_length=50, verbose_name='课程地点')),
                ('xqj', models.IntegerField(default=0, verbose_name='星期几')),
                ('skjc', models.IntegerField(default=0, verbose_name='上课开始')),
                ('skcd', models.IntegerField(default=0, verbose_name='上课长度')),
                ('qszs', models.IntegerField(default=0, verbose_name='起始周数')),
                ('jszs', models.IntegerField(default=0, verbose_name='结束周数')),
                ('dsz', models.IntegerField(default=0, verbose_name='单双周')),
                ('extra', models.TextField(verbose_name='課程信息')),
            ],
        ),
        migrations.CreateModel(
            name='gradeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_id', models.CharField(max_length=30, verbose_name='课程号')),
                ('unique_key', models.CharField(default='', max_length=50, verbose_name='学号+课程号')),
                ('subject', models.CharField(max_length=30, verbose_name='课程名称')),
                ('property', models.CharField(max_length=30, verbose_name='课程性质')),
                ('grade', models.CharField(max_length=30, verbose_name='分数')),
            ],
        ),
        migrations.CreateModel(
            name='Guake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=50, verbose_name='课程号')),
                ('Name', models.CharField(max_length=50, verbose_name='课程名')),
                ('Number', models.CharField(max_length=50, verbose_name='人基数')),
                ('Category', models.CharField(max_length=50, verbose_name='课程类型')),
                ('P0_59', models.CharField(max_length=50, verbose_name='0-59')),
                ('P60_69', models.CharField(max_length=50, verbose_name='60-69')),
                ('P70_79', models.CharField(max_length=50, verbose_name='70-79')),
                ('P80_89', models.CharField(max_length=50, verbose_name='80-89')),
                ('P90_100', models.CharField(max_length=50, verbose_name='90-100')),
            ],
        ),
        migrations.CreateModel(
            name='student_Id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xuehao', models.CharField(max_length=30, verbose_name='学号')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
