# Generated by Django 2.1.5 on 2019-03-09 13:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail_article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailarticle',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
