# Generated by Django 2.1.5 on 2019-03-11 03:59

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail_article', '0002_auto_20190309_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailarticle',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
