# Generated by Django 2.1.7 on 2019-03-16 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail_article', '0003_auto_20190311_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailarticle',
            options={'verbose_name': '详情文章', 'verbose_name_plural': '详情文章'},
        ),
    ]
