# Generated by Django 2.2 on 2019-11-09 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ahuUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sno', models.CharField(max_length=12, verbose_name='学号')),
                ('userAvatar', models.ImageField(blank=True, default='', null=True, upload_to='user_avatar', verbose_name='学生微信头像')),
                ('unread_num', models.IntegerField(default=0, verbose_name='未阅读消息数')),
            ],
            options={
                'verbose_name': '用户信息（动态）',
                'verbose_name_plural': '用户信息（动态）',
            },
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='评论')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('like_num', models.IntegerField(default=0, verbose_name='点赞数')),
            ],
            options={
                'verbose_name': '评论（动态）',
                'verbose_name_plural': '评论（动态）',
            },
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excerpt', models.CharField(max_length=300, verbose_name='动态内容')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('like_num', models.IntegerField(default=0, verbose_name='点赞数')),
                ('img', models.ImageField(blank=True, default='', null=True, upload_to='action_img', verbose_name='图片1')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.ahuUser')),
            ],
            options={
                'verbose_name': '已发内容（动态）',
                'verbose_name_plural': '已发内容（动态）',
            },
        ),
        migrations.CreateModel(
            name='UserCommentLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_comments', to='community.ArticleComment', verbose_name='喜欢的评论')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.ahuUser')),
            ],
            options={
                'verbose_name': '评论点赞表',
                'verbose_name_plural': '评论点赞表',
            },
        ),
        migrations.CreateModel(
            name='UserActionLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_action', to='community.UserAction', verbose_name='喜欢的文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.ahuUser')),
            ],
            options={
                'verbose_name': '动态点赞表',
                'verbose_name_plural': '动态点赞表',
            },
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.UserAction', verbose_name='评论文章'),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.ahuUser', verbose_name='评论者'),
        ),
        migrations.CreateModel(
            name='allNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement', models.CharField(max_length=20, verbose_name='动作名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='动作起始时间')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.UserAction', verbose_name='动作目标文章')),
                ('movementer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movementer', to='community.ahuUser', verbose_name='动作发起者')),
                ('noticeer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noticeer', to='community.ahuUser', verbose_name='动作通知的人')),
            ],
            options={
                'verbose_name': '动态通知表',
                'verbose_name_plural': '动态通知表',
            },
        ),
    ]
