# Generated by Django 2.2 on 2019-12-05 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahuuser',
            name='wx_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='微信名称'),
        ),
        migrations.AddField(
            model_name='useraction',
            name='position',
            field=models.CharField(default='', max_length=300, verbose_name='地点'),
        ),
        migrations.CreateModel(
            name='stickieAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.UserAction')),
            ],
        ),
    ]
