# Generated by Django 2.2 on 2019-12-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20191205_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stickieaction',
            name='action',
        ),
        migrations.AddField(
            model_name='stickieaction',
            name='action_id',
            field=models.IntegerField(default=0, verbose_name='文章id'),
        ),
    ]
