# Generated by Django 2.2 on 2020-01-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20200124_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiontype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='动态种类名称'),
        ),
    ]
