# Generated by Django 2.2 on 2020-01-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_auto_20200124_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraction',
            name='position',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='地点'),
        ),
    ]
