# Generated by Django 2.1.5 on 2019-03-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='top_article_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('img', models.ImageField(upload_to='img', verbose_name='轮播图图片')),
                ('detail', models.CharField(max_length=500, verbose_name='轮播图内容')),
            ],
            options={
                'verbose_name': '顶部轮播图',
                'verbose_name_plural': '顶部轮播图',
            },
        ),
        migrations.DeleteModel(
            name='top_article',
        ),
    ]
