# Generated by Django 2.2 on 2019-11-09 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AhuAdvert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weixin_link', models.CharField(max_length=100, verbose_name='推文连接')),
                ('background_img', models.ImageField(blank=True, default='', null=True, upload_to='weixin_background_img', verbose_name='背景图')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('ask', models.CharField(max_length=2000, verbose_name='问题')),
                ('answer', models.CharField(max_length=2000, verbose_name='回答')),
                ('create_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolLife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=20, verbose_name='作者名')),
                ('avatar', models.ImageField(blank=True, default='', null=True, upload_to='user_avatar', verbose_name='作者头像')),
                ('weixin_link', models.CharField(max_length=100, verbose_name='推文连接')),
                ('background_img', models.ImageField(blank=True, default='', null=True, upload_to='weixin_background_img', verbose_name='背景图')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolLife_TJLG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=20, verbose_name='作者名')),
                ('avatar', models.ImageField(blank=True, default='', null=True, upload_to='user_avatar', verbose_name='作者头像')),
                ('weixin_link', models.CharField(max_length=100, verbose_name='推文连接')),
                ('background_img', models.ImageField(blank=True, default='', null=True, upload_to='weixin_background_img', verbose_name='背景图')),
            ],
            options={
                'verbose_name': '校园生活(天津理工)',
                'verbose_name_plural': '校园生活(天津理工)',
            },
        ),
        migrations.CreateModel(
            name='TJLGAdvert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weixin_link', models.CharField(max_length=100, verbose_name='推文连接')),
                ('background_img', models.ImageField(blank=True, default='', null=True, upload_to='weixin_background_img', verbose_name='背景图')),
            ],
            options={
                'verbose_name': '大个广告(天津理工)',
                'verbose_name_plural': '大个广告(天津理工)',
            },
        ),
        migrations.CreateModel(
            name='TJLG_Article_Pyspider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('detail_url', models.URLField(blank=True, default='', null=True, verbose_name='文章详情链接--(可选)(注:只能添加已关联公众号文章链接或通过本网站发布的详情文章链接):')),
                ('excerpt', models.TextField(verbose_name='摘要')),
                ('created_time', models.DateTimeField()),
                ('last_updated_time', models.DateTimeField()),
                ('img1', models.ImageField(blank=True, default='', null=True, upload_to='img', verbose_name='图片1')),
                ('img2', models.ImageField(blank=True, default='', null=True, upload_to='img', verbose_name='图片2')),
                ('img3', models.ImageField(blank=True, default='', null=True, upload_to='img', verbose_name='图片3')),
                ('img4', models.ImageField(blank=True, default='', null=True, upload_to='img', verbose_name='图片4')),
                ('img5', models.ImageField(blank=True, default='', null=True, upload_to='img', verbose_name='图片5')),
                ('img6', models.ImageField(blank=True, default='', null=True, upload_to='img', verbose_name='图片6')),
                ('img7', models.ImageField(blank=True, default='', null=True, upload_to='img', verbose_name='图片7')),
                ('img8', models.ImageField(blank=True, default='', null=True, upload_to='img', verbose_name='图片8')),
                ('img9', models.ImageField(blank=True, default='', null=True, upload_to='img', verbose_name='图片9')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
            ],
            options={
                'verbose_name': '教务通知（天津理工）',
                'verbose_name_plural': '教务通知（天津理工）',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('detail_url', models.URLField(blank=True, default='', null=True, verbose_name='文章详情链接--(可选)(注:只能添加已关联公众号文章链接或通过本网站发布的详情文章链接):')),
                ('excerpt', models.TextField(verbose_name='摘要')),
                ('created_time', models.DateTimeField()),
                ('last_updated_time', models.DateTimeField()),
                ('img1', models.ImageField(blank=True, default='', null=True, upload_to='img', verbose_name='图片1')),
                ('img2', models.ImageField(blank=True, default='', null=True, upload_to='img', verbose_name='图片2')),
                ('img3', models.ImageField(blank=True, default='', null=True, upload_to='img', verbose_name='图片3')),
                ('img4', models.ImageField(blank=True, default='', null=True, upload_to='img', verbose_name='图片4')),
                ('img5', models.ImageField(blank=True, default='', null=True, upload_to='img', verbose_name='图片5')),
                ('img6', models.ImageField(blank=True, default='', null=True, upload_to='img', verbose_name='图片6')),
                ('img7', models.ImageField(blank=True, default='', null=True, upload_to='img', verbose_name='图片7')),
                ('img8', models.ImageField(blank=True, default='', null=True, upload_to='img', verbose_name='图片8')),
                ('img9', models.ImageField(blank=True, default='', null=True, upload_to='img', verbose_name='图片9')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
            ],
            options={
                'verbose_name': '社团动态（天津理工）',
                'verbose_name_plural': '社团动态（天津理工）',
            },
        ),
    ]
