# Generated by Django 2.2 on 2019-11-09 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '校招实习（天津理工）', 'verbose_name_plural': '校招实习（天津理工）'},
        ),
        migrations.AlterModelOptions(
            name='tjlg_article_pyspider',
            options={'verbose_name': '资讯通知（天津理工）', 'verbose_name_plural': '资讯通知（天津理工）'},
        ),
    ]
