# Generated by Django 2.1.5 on 2019-03-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_article', '0002_auto_20190308_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='excerpt',
        ),
        migrations.AddField(
            model_name='article',
            name='img1',
            field=models.ImageField(default='', upload_to='img', verbose_name='图片1'),
        ),
        migrations.AddField(
            model_name='article',
            name='img2',
            field=models.ImageField(default='', upload_to='img', verbose_name='图片2'),
        ),
        migrations.AddField(
            model_name='article',
            name='img3',
            field=models.ImageField(default='', upload_to='img', verbose_name='图片3'),
        ),
        migrations.AddField(
            model_name='article',
            name='img4',
            field=models.ImageField(default='', upload_to='img', verbose_name='图片4'),
        ),
        migrations.AddField(
            model_name='article',
            name='img5',
            field=models.ImageField(default='', upload_to='img', verbose_name='图片5'),
        ),
        migrations.AddField(
            model_name='article',
            name='img6',
            field=models.ImageField(default='', upload_to='img', verbose_name='图片6'),
        ),
        migrations.AddField(
            model_name='article',
            name='img7',
            field=models.ImageField(default='', upload_to='img', verbose_name='图片7'),
        ),
        migrations.AddField(
            model_name='article',
            name='img8',
            field=models.ImageField(default='', upload_to='img', verbose_name='图片8'),
        ),
        migrations.AddField(
            model_name='article',
            name='img9',
            field=models.ImageField(default='', upload_to='img', verbose_name='图片9'),
        ),
        migrations.AlterField(
            model_name='article',
            name='detail_url',
            field=models.URLField(verbose_name='文章详情链接--(可选)(注:只能添加已关联公众号文章链接或通过本网站发布的详情文章链接):'),
        ),
    ]
