# Generated by Django 2.1.5 on 2019-03-12 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_article', '0006_auto_20190308_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile'),
        ),
        migrations.AlterField(
            model_name='article',
            name='detail_url',
            field=models.URLField(blank=True, default='None', null=True, verbose_name='文章详情链接--(可选)(注:只能添加已关联公众号文章链接或通过本网站发布的详情文章链接):'),
        ),
    ]
