# Generated by Django 2.1.5 on 2019-03-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_article', '0008_auto_20190312_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='detail_url',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='文章详情链接--(可选)(注:只能添加已关联公众号文章链接或通过本网站发布的详情文章链接):'),
        ),
    ]
