# Generated by Django 2.1.7 on 2019-03-16 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_article', '0010_auto_20190316_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '普通文章', 'verbose_name_plural': '普通文章'},
        ),
    ]
