# Generated by Django 2.2 on 2019-10-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=30, verbose_name='活动名')),
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='题目（选填）')),
                ('speaker', models.CharField(max_length=30, verbose_name='主讲人')),
                ('host', models.CharField(blank=True, max_length=30, null=True, verbose_name='主持人（选填）')),
                ('time', models.DateTimeField(verbose_name='时间(日期格式必须为2019/03/17，时间格式必须为13:32)')),
                ('start_time', models.IntegerField(choices=[(1, '第一节课'), (2, '第二节课'), (3, '第三节课'), (4, '第四节课'), (5, '第五节课'), (6, '第六节课'), (7, '第七节课'), (8, '第八节课'), (9, '第九节课')], verbose_name='开始时间')),
                ('length', models.IntegerField(choices=[(4, '四节课'), (1, '二节课'), (2, '二节课'), (3, '三节课')], verbose_name='持续时长')),
                ('location', models.CharField(max_length=50, verbose_name='地点')),
                ('intro', models.CharField(default='暂无主讲人简介', max_length=120, verbose_name='主讲人简介(最多120字)')),
            ],
            options={
                'verbose_name': '课表自定义显示内容',
                'verbose_name_plural': '课表自定义显示内容',
            },
        ),
    ]
