# Generated by Django 2.1.7 on 2019-03-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectureApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='length',
            field=models.IntegerField(choices=[(3, '三节课'), (2, '二节课'), (1, '二节课'), (4, '四节课')], verbose_name='持续时长'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='time',
            field=models.DateTimeField(verbose_name='时间'),
        ),
    ]
