# Generated by Django 2.1.7 on 2019-03-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectureApi', '0002_auto_20190316_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='host',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='主持人（选填）'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='intro',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='主讲人简介(选填)(最多120字)'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='length',
            field=models.IntegerField(choices=[(4, '四节课'), (3, '三节课'), (2, '二节课'), (1, '二节课')], verbose_name='持续时长'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='time',
            field=models.DateTimeField(verbose_name='时间(日期格式必须为2019/03/17，时间格式必须为13:32)'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='题目（选填）'),
        ),
    ]
