# Generated by Django 2.1.7 on 2019-03-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectureApi', '0003_auto_20190316_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'verbose_name': '课表自定义显示内容', 'verbose_name_plural': '课表自定义显示内容'},
        ),
        migrations.AlterField(
            model_name='lecture',
            name='length',
            field=models.IntegerField(choices=[(1, '二节课'), (2, '二节课'), (4, '四节课'), (3, '三节课')], verbose_name='持续时长'),
        ),
    ]
