# Generated by Django 2.1.7 on 2019-03-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectureApi', '0006_auto_20190317_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='length',
            field=models.IntegerField(choices=[(3, '三节课'), (2, '二节课'), (1, '二节课'), (4, '四节课')], verbose_name='持续时长'),
        ),
    ]
