# Generated by Django 2.1.7 on 2019-03-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectureApi', '0007_auto_20190317_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='length',
            field=models.IntegerField(choices=[(4, '四节课'), (1, '二节课'), (2, '二节课'), (3, '三节课')], verbose_name='持续时长'),
        ),
    ]
