# Generated by Django 2.2 on 2019-12-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectureApi', '0008_auto_20191205_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='length',
            field=models.IntegerField(choices=[(4, '四节课'), (2, '二节课'), (1, '二节课'), (3, '三节课')], verbose_name='持续时长'),
        ),
    ]
