# Generated by Django 2.2 on 2020-01-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectureApi', '0010_auto_20200124_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='length',
            field=models.IntegerField(choices=[(1, '二节课'), (4, '四节课'), (3, '三节课'), (2, '二节课')], verbose_name='持续时长'),
        ),
    ]
