# Generated by Django 2.2 on 2020-01-24 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectureApi', '0010_auto_20200124_1420'),
        ('lectureApi', '0012_auto_20200124_1033'),
    ]

    operations = [
    ]
