# Generated by Django 2.1.5 on 2020-08-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectureApi', '0015_auto_20200124_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='length',
            field=models.IntegerField(choices=[(1, '二节课'), (2, '二节课'), (4, '四节课'), (3, '三节课')], verbose_name='持续时长'),
        ),
    ]
