# Generated by Django 2.2 on 2020-08-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectureApi', '0016_auto_20200827_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='length',
            field=models.IntegerField(choices=[(4, '四节课'), (3, '三节课'), (1, '二节课'), (2, '二节课')], verbose_name='持续时长'),
        ),
    ]
