# Generated by Django 2.2 on 2021-09-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectureApi', '0017_auto_20200830_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='length',
            field=models.IntegerField(choices=[(3, '三节课'), (4, '四节课'), (2, '二节课'), (1, '二节课')], verbose_name='持续时长'),
        ),
    ]
