# Generated by Django 2.2 on 2019-10-24 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='维修状态名')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Gongdan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gongdanid', models.CharField(blank=True, max_length=50, null=True, verbose_name='工单号')),
                ('sno', models.CharField(max_length=50, verbose_name='学号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('excerpt', models.TextField(blank=True, null=True, verbose_name='故障描述')),
                ('reply', models.TextField(blank=True, null=True, verbose_name='后勤回复')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('phone_num', models.CharField(default='', max_length=50, verbose_name='手机号')),
                ('status', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='houqinApi.StatusName')),
            ],
            options={
                'verbose_name': '工单',
                'verbose_name_plural': '工单',
            },
        ),
    ]
